/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package sms_project;

import java.sql.*;
import java.sql.PreparedStatement;
import javax.swing.*;

/**
 *
 * @author ASUS
 */
public class forgot_reset extends javax.swing.JFrame {

    /**
     * Creates new form forgot_reset
     */
    public forgot_reset() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        back = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        user_id = new javax.swing.JTextField();
        sec_question = new javax.swing.JTextField();
        old_password = new javax.swing.JTextField();
        sec_answer = new javax.swing.JTextField();
        new_password = new javax.swing.JTextField();
        conform_password = new javax.swing.JTextField();
        get_password = new javax.swing.JButton();
        get_question = new javax.swing.JButton();
        reset = new javax.swing.JButton();
        close1 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Forgot & Reset");
        setMaximumSize(new java.awt.Dimension(653, 679));
        setMinimumSize(new java.awt.Dimension(653, 679));
        setPreferredSize(new java.awt.Dimension(653, 679));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Serif", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 0));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/forgot and reset password icon.jpg"))); // NOI18N
        jLabel1.setText("FORGOT & RESET PAGE");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(122, 6, -1, 76));

        back.setBackground(new java.awt.Color(255, 153, 102));
        back.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        back.setText("<- BACK");
        back.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        back.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        getContentPane().add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 20, 70, 31));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("USER-ID :");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(191, 129, 130, 29));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("SECURITY ANSWER :");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(99, 295, -1, 29));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("SECURITY QUESTION :");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(85, 221, -1, 29));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("OLD PASSWORD :");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(121, 377, -1, 29));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("NEW PASSWORD :");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(116, 439, -1, 29));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("CONFORM PASSWORD :");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(66, 503, -1, 29));

        user_id.setFont(new java.awt.Font("Segoe UI Variable", 1, 18)); // NOI18N
        user_id.setBorder(null);
        user_id.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        getContentPane().add(user_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(327, 128, 252, 32));

        sec_question.setFont(new java.awt.Font("Segoe UI Variable", 1, 18)); // NOI18N
        sec_question.setBorder(null);
        sec_question.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        getContentPane().add(sec_question, new org.netbeans.lib.awtextra.AbsoluteConstraints(327, 220, 252, 32));

        old_password.setFont(new java.awt.Font("Segoe UI Variable", 1, 18)); // NOI18N
        old_password.setBorder(null);
        old_password.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        getContentPane().add(old_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(327, 368, 252, 32));

        sec_answer.setFont(new java.awt.Font("Segoe UI Variable", 1, 18)); // NOI18N
        sec_answer.setBorder(null);
        sec_answer.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        getContentPane().add(sec_answer, new org.netbeans.lib.awtextra.AbsoluteConstraints(327, 280, 252, 32));

        new_password.setFont(new java.awt.Font("Segoe UI Variable", 1, 18)); // NOI18N
        new_password.setBorder(null);
        new_password.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        getContentPane().add(new_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(327, 433, 252, 32));

        conform_password.setFont(new java.awt.Font("Segoe UI Variable", 1, 18)); // NOI18N
        conform_password.setBorder(null);
        conform_password.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        getContentPane().add(conform_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(327, 500, 252, 32));

        get_password.setBackground(new java.awt.Color(204, 255, 204));
        get_password.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        get_password.setText("Get");
        get_password.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        get_password.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        get_password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                get_passwordActionPerformed(evt);
            }
        });
        getContentPane().add(get_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(446, 324, 55, -1));

        get_question.setBackground(new java.awt.Color(204, 255, 204));
        get_question.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        get_question.setText("Get ");
        get_question.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        get_question.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        get_question.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                get_questionActionPerformed(evt);
            }
        });
        getContentPane().add(get_question, new org.netbeans.lib.awtextra.AbsoluteConstraints(446, 176, 56, -1));

        reset.setBackground(new java.awt.Color(0, 204, 255));
        reset.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        reset.setText("RESET");
        reset.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        reset.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetActionPerformed(evt);
            }
        });
        getContentPane().add(reset, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 550, 126, 31));

        close1.setBackground(new java.awt.Color(255, 0, 0));
        close1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        close1.setText("CLOSE");
        close1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        close1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        close1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                close1ActionPerformed(evt);
            }
        });
        getContentPane().add(close1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 590, 126, 31));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/forgot and reset password bg.png"))); // NOI18N
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 650, 680));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        this.setVisible(false);
        new sign_in_page().setVisible(true);
    }//GEN-LAST:event_backActionPerformed

    private void resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetActionPerformed
        String uid = user_id.getText();
        String old_pwd = old_password.getText();
        String sec_ques = sec_question.getText();
        String sec_ans = sec_answer.getText();
        String new_pwd = new_password.getText();
        String conform_pwd = conform_password.getText();
        if (!uid.isEmpty() && !old_pwd.isEmpty() && !sec_ques.isEmpty() && !sec_ans.isEmpty() && !conform_pwd.isEmpty()
                && !(old_pwd.equals(conform_pwd)) && new_pwd.equals(conform_pwd)) {
            try (Connection conn = JDBC.con(); PreparedStatement pst = conn.prepareStatement("sp_sms_admin_password_update ?,?")) {
                pst.setString(1, uid);
                pst.setString(2, conform_pwd);
                int result = pst.executeUpdate();
                if (result == 1) {
                    JOptionPane.showMessageDialog(this, "Password Updated");
                    this.setVisible(false);
                    new forgot_reset().setVisible(true);
                } else {
                    JOptionPane.showMessageDialog(this, "Password  not Update");
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, e);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Something Error");
        }


    }//GEN-LAST:event_resetActionPerformed

    private void get_questionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_get_questionActionPerformed
        String uid = user_id.getText();
        if (!uid.isEmpty()) {
            try (Connection conn = JDBC.con(); PreparedStatement pst = conn.prepareStatement("sp_sms_admin_get_question ?")) {
                pst.setString(1, uid);
                ResultSet rs = pst.executeQuery();
                if (rs.next()) {
                    sec_question.setText(rs.getString("security_question"));

                } else {
                    JOptionPane.showMessageDialog(this, "Invalid User-ID");
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, e);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Enter User-ID");
        }
    }//GEN-LAST:event_get_questionActionPerformed

    private void get_passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_get_passwordActionPerformed
        String sec_ans = sec_answer.getText();
        if (!sec_ans.isEmpty()) {
            try (Connection conn = JDBC.con(); PreparedStatement pst = conn.prepareStatement(" sp_sms_admin_get_password ?")) {
                pst.setString(1, sec_ans);
                ResultSet rs = pst.executeQuery();
                if (rs.next()) {
                    old_password.setText(rs.getString("password"));

                } else {
                    JOptionPane.showMessageDialog(this, "Incorrect Security-Answer");
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, e);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Enter Security-Answer");
        }
    }//GEN-LAST:event_get_passwordActionPerformed

    private void close1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_close1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_close1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(forgot_reset.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(forgot_reset.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(forgot_reset.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(forgot_reset.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new forgot_reset().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JButton close1;
    private javax.swing.JTextField conform_password;
    private javax.swing.JButton get_password;
    private javax.swing.JButton get_question;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField new_password;
    private javax.swing.JTextField old_password;
    private javax.swing.JButton reset;
    private javax.swing.JTextField sec_answer;
    private javax.swing.JTextField sec_question;
    private javax.swing.JTextField user_id;
    // End of variables declaration//GEN-END:variables
}
