/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package sms_project;

/**
 *
 * @author ASUS
 */
public class main_page extends javax.swing.JFrame {

    /**
     * Creates new form main_page
     */
    public main_page() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        student_page = new javax.swing.JButton();
        details_btn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        close = new javax.swing.JButton();
        course_btn1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MAIN PAGE");
        setMaximumSize(new java.awt.Dimension(745, 554));
        setMinimumSize(new java.awt.Dimension(745, 554));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        student_page.setBackground(new java.awt.Color(255, 255, 153));
        student_page.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        student_page.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/student icon (1).jpg"))); // NOI18N
        student_page.setText("STUDENT INFO.");
        student_page.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        student_page.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        student_page.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                student_pageActionPerformed(evt);
            }
        });
        getContentPane().add(student_page, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 180, 244, 63));

        details_btn.setBackground(new java.awt.Color(255, 204, 204));
        details_btn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        details_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/details icon.png"))); // NOI18N
        details_btn.setText("DETAILS");
        details_btn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        details_btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        details_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                details_btnActionPerformed(evt);
            }
        });
        getContentPane().add(details_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 380, 244, 60));

        jLabel1.setFont(new java.awt.Font("Serif", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 0));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/main page icon.jpg"))); // NOI18N
        jLabel1.setText("SMS MAIN PAGE");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(223, 6, 312, -1));

        close.setBackground(new java.awt.Color(255, 0, 0));
        close.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        close.setText("CLOSE");
        close.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        close.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeActionPerformed(evt);
            }
        });
        getContentPane().add(close, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 500, 126, 31));

        course_btn1.setBackground(new java.awt.Color(204, 204, 255));
        course_btn1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        course_btn1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/course icon.jpg"))); // NOI18N
        course_btn1.setText("COURSE INFO.");
        course_btn1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        course_btn1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        course_btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                course_btn1ActionPerformed(evt);
            }
        });
        getContentPane().add(course_btn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 280, 244, 63));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/main page bg.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 740, 560));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void closeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_closeActionPerformed

    private void student_pageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_student_pageActionPerformed
           this.setVisible(false);
         new Student_page().setVisible(true);
    }//GEN-LAST:event_student_pageActionPerformed

    private void details_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_details_btnActionPerformed
        this.setVisible(false);
         new details_page().setVisible(true);
    }//GEN-LAST:event_details_btnActionPerformed

    private void course_btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_course_btn1ActionPerformed
          this.setVisible(false);
         new course_page().setVisible(true);
    }//GEN-LAST:event_course_btn1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(main_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(main_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(main_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(main_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new main_page().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton close;
    private javax.swing.JButton course_btn1;
    private javax.swing.JButton details_btn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton student_page;
    // End of variables declaration//GEN-END:variables
}
