/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package sms_project;

import java.sql.*;
import java.sql.PreparedStatement;
import javax.swing.*;

/**
 *
 * @author ASUS
 */
public class sign_up_page extends javax.swing.JFrame {

    /**
     * Creates new form sign_up_page
     */
    public sign_up_page() {
        initComponents();
    }

    private boolean isExists(String id) {
        try (Connection conn = JDBC.con(); PreparedStatement pst = conn.prepareStatement("sp_sms_admin_isExists ?")) {
            pst.setString(1, id);
            ResultSet rs = pst.executeQuery();
            if (rs.next()) {
                return rs.getInt(1) > 0;
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e);
        }
        return false;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        back = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        back1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        password = new javax.swing.JTextField();
        name = new javax.swing.JTextField();
        user_id = new javax.swing.JTextField();
        security_answer = new javax.swing.JTextField();
        security_question = new javax.swing.JTextField();
        sign_up = new javax.swing.JButton();
        close = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        back.setBackground(new java.awt.Color(255, 153, 102));
        back.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        back.setText("<- BACK");
        back.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        back.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sign-Up page");
        setMaximumSize(new java.awt.Dimension(668, 604));
        setMinimumSize(new java.awt.Dimension(668, 604));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Serif", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 0));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/sign up icon.png"))); // NOI18N
        jLabel1.setText("SMS SIGN-UP PAGE");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(177, 6, -1, -1));

        back1.setBackground(new java.awt.Color(255, 153, 102));
        back1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        back1.setText("<- BACK");
        back1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        back1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        back1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                back1ActionPerformed(evt);
            }
        });
        getContentPane().add(back1, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 20, 70, 31));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("NAME :");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(195, 197, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("USER-ID :");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(177, 137, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("SECURITY QUESTION :");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(69, 345, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("PASSWORD :");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(147, 268, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("SECURITY ANSWER :");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(83, 406, -1, -1));

        password.setFont(new java.awt.Font("Segoe UI Variable", 1, 18)); // NOI18N
        getContentPane().add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(321, 268, 253, -1));

        name.setFont(new java.awt.Font("Segoe UI Variable", 1, 18)); // NOI18N
        getContentPane().add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(321, 203, 253, -1));

        user_id.setFont(new java.awt.Font("Segoe UI Variable", 1, 18)); // NOI18N
        getContentPane().add(user_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(321, 137, 253, -1));

        security_answer.setFont(new java.awt.Font("Segoe UI Variable", 1, 18)); // NOI18N
        getContentPane().add(security_answer, new org.netbeans.lib.awtextra.AbsoluteConstraints(321, 403, 253, -1));

        security_question.setFont(new java.awt.Font("Segoe UI Variable", 1, 18)); // NOI18N
        getContentPane().add(security_question, new org.netbeans.lib.awtextra.AbsoluteConstraints(321, 339, 253, -1));

        sign_up.setBackground(new java.awt.Color(204, 255, 204));
        sign_up.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        sign_up.setText("SIGN-UP");
        sign_up.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        sign_up.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        sign_up.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sign_upActionPerformed(evt);
            }
        });
        getContentPane().add(sign_up, new org.netbeans.lib.awtextra.AbsoluteConstraints(262, 489, 126, 32));

        close.setBackground(new java.awt.Color(255, 0, 0));
        close.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        close.setText("CLOSE");
        close.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        close.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeActionPerformed(evt);
            }
        });
        getContentPane().add(close, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 550, 126, 31));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/sign-up bg.jpg"))); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 670, 610));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_backActionPerformed

    private void back1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_back1ActionPerformed
        this.setVisible(false);
        new sign_in_page().setVisible(true);
    }//GEN-LAST:event_back1ActionPerformed

    private void closeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_closeActionPerformed

    private void sign_upActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sign_upActionPerformed
        String userid = user_id.getText();
        String Name = name.getText();
        String pwd = password.getText();
        String sec_question = security_question.getText();
        String sec_answer = security_answer.getText();

        if (!userid.isEmpty() && !Name.isEmpty() && !pwd.isEmpty() && !sec_question.isEmpty() && !sec_answer.isEmpty()) {
            if (!(isExists(userid))) {
                try (Connection conn = JDBC.con(); PreparedStatement pst = conn.prepareStatement("sp_sms_admin_insert ?,?,?,?,?")) {
                    pst.setString(1, userid);
                    pst.setString(2, Name);
                    pst.setString(3, pwd);
                    pst.setString(4, sec_question);
                    pst.setString(5, sec_answer);

                    int result = pst.executeUpdate();
                    if (result == 1) {
                        JOptionPane.showMessageDialog(this, "Signed-Up");
                        this.setVisible(false);
                        new sign_in_page().setVisible(true);
                    } else {
                        JOptionPane.showMessageDialog(this, "Sign-Up Error");
                    }

                } catch (Exception e) {
                    JOptionPane.showMessageDialog(this, e);
                }
            } else {
                JOptionPane.showMessageDialog(this, "Same ID Already Exixts");
            }
        } else {
            JOptionPane.showMessageDialog(this, "Enter All Datas");
        }


    }//GEN-LAST:event_sign_upActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(sign_up_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(sign_up_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(sign_up_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(sign_up_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new sign_up_page().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JButton back1;
    private javax.swing.JButton close;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField name;
    private javax.swing.JTextField password;
    private javax.swing.JTextField security_answer;
    private javax.swing.JTextField security_question;
    private javax.swing.JButton sign_up;
    private javax.swing.JTextField user_id;
    // End of variables declaration//GEN-END:variables
}
