/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package sms_project;

import java.sql.*;
import javax.swing.*;

/**
 *
 * @author ASUS
 */
public class sign_in_page extends javax.swing.JFrame {

    /**
     * Creates new form sign_in_page
     */
    public sign_in_page() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        user_id = new javax.swing.JTextField();
        sign_up = new javax.swing.JButton();
        forgot_reset = new javax.swing.JButton();
        close = new javax.swing.JButton();
        sign_in = new javax.swing.JButton();
        show = new javax.swing.JCheckBox();
        password = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sign-in page");
        setMaximumSize(new java.awt.Dimension(736, 577));
        setMinimumSize(new java.awt.Dimension(736, 577));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Serif", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 0));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/sign in icon.png"))); // NOI18N
        jLabel1.setText("SMS SIGN-IN PAGE");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 10, 410, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("PASSWORD :");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(121, 260, 154, 28));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("USER-ID :");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(151, 177, 154, 28));

        user_id.setFont(new java.awt.Font("Segoe UI Variable", 1, 18)); // NOI18N
        getContentPane().add(user_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(311, 173, 284, 37));

        sign_up.setBackground(new java.awt.Color(255, 255, 204));
        sign_up.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        sign_up.setText("SIGN-UP");
        sign_up.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        sign_up.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        sign_up.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sign_upActionPerformed(evt);
            }
        });
        getContentPane().add(sign_up, new org.netbeans.lib.awtextra.AbsoluteConstraints(526, 450, 126, 31));

        forgot_reset.setBackground(new java.awt.Color(255, 255, 204));
        forgot_reset.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        forgot_reset.setText("FORGOT & RESET");
        forgot_reset.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        forgot_reset.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        forgot_reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                forgot_resetActionPerformed(evt);
            }
        });
        getContentPane().add(forgot_reset, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 450, 150, 31));

        close.setBackground(new java.awt.Color(255, 0, 0));
        close.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        close.setText("CLOSE");
        close.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        close.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeActionPerformed(evt);
            }
        });
        getContentPane().add(close, new org.netbeans.lib.awtextra.AbsoluteConstraints(311, 450, 126, 31));

        sign_in.setBackground(new java.awt.Color(204, 255, 204));
        sign_in.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        sign_in.setText("SIGN-IN");
        sign_in.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        sign_in.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        sign_in.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sign_inActionPerformed(evt);
            }
        });
        getContentPane().add(sign_in, new org.netbeans.lib.awtextra.AbsoluteConstraints(311, 362, 126, 31));

        show.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        show.setForeground(new java.awt.Color(255, 255, 255));
        show.setText("show");
        show.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        show.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showActionPerformed(evt);
            }
        });
        getContentPane().add(show, new org.netbeans.lib.awtextra.AbsoluteConstraints(551, 305, 70, 30));

        password.setFont(new java.awt.Font("Segoe UI Variable", 1, 18)); // NOI18N
        password.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        password.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        getContentPane().add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(311, 252, 284, 36));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/login-bg.jpg"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 740, 580));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void closeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_closeActionPerformed

    private void forgot_resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_forgot_resetActionPerformed
        this.setVisible(false);
        new forgot_reset().setVisible(true);
    }//GEN-LAST:event_forgot_resetActionPerformed

    private void sign_upActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sign_upActionPerformed
        this.setVisible(false);
        new sign_up_page().setVisible(true);
    }//GEN-LAST:event_sign_upActionPerformed

    private void sign_inActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sign_inActionPerformed
        String uid = user_id.getText();
        String pwd = password.getText();
        if (!uid.isEmpty() && !pwd.isEmpty()) {
            try (Connection conn = JDBC.con(); PreparedStatement pst = conn.prepareStatement("sp_sms_admin_signin ?,?")) {
                pst.setString(1, uid);
                pst.setString(2, pwd);
                ResultSet rs =  pst.executeQuery();
                if(rs.next())
                {
                this.setVisible(false);
                new main_page().setVisible(true);
                }
                else
                {
                   JOptionPane.showMessageDialog(this, "Sign-in Error"); 
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, e);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Enter All Fields");
        }
    }//GEN-LAST:event_sign_inActionPerformed

    private void showActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showActionPerformed
        if (show.isSelected()) {
            password.setEchoChar((char) 0);
        } else {
            password.setEchoChar('*');
        }
    }//GEN-LAST:event_showActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(sign_in_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(sign_in_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(sign_in_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(sign_in_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new sign_in_page().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton close;
    private javax.swing.JButton forgot_reset;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPasswordField password;
    private javax.swing.JCheckBox show;
    private javax.swing.JButton sign_in;
    private javax.swing.JButton sign_up;
    private javax.swing.JTextField user_id;
    // End of variables declaration//GEN-END:variables
}
