/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package sms_project;

import java.awt.Component;
import java.awt.Image;
import java.io.File;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ASUS
 */
public class Student_page extends javax.swing.JFrame {

    /**
     * Creates new form Student_page
     */
    public Student_page() {
        initComponents();
        student_tbl.getColumnModel().getColumn(8).setCellRenderer(new Student_page.ImageRenderer());
    }

    private static class ImageRenderer extends DefaultTableCellRenderer {

        @Override
        public Component getTableCellRendererComponent(JTable table, Object value, boolean isSelected, boolean hasFocus, int row, int column) {
            if (value instanceof ImageIcon) {
                JLabel label = new JLabel((ImageIcon) value);
                label.setHorizontalAlignment(SwingConstants.CENTER);
                return label;
            }
            return super.getTableCellRendererComponent(table, value, isSelected, hasFocus, row, column);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        student_tbl = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        uid1 = new javax.swing.JTextField();
        fetch1 = new javax.swing.JButton();
        back1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        path1 = new javax.swing.JTextField();
        name1 = new javax.swing.JTextField();
        mobile1 = new javax.swing.JTextField();
        email1 = new javax.swing.JTextField();
        dob11 = new com.toedter.calendar.JDateChooser();
        male1 = new javax.swing.JRadioButton();
        female1 = new javax.swing.JRadioButton();
        course1 = new javax.swing.JComboBox<>();
        photo1 = new javax.swing.JLabel();
        clear1 = new javax.swing.JButton();
        close1 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Student page");
        setMaximumSize(new java.awt.Dimension(1077, 711));
        setMinimumSize(new java.awt.Dimension(1077, 711));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        student_tbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "User_ID", "Name", "Email-ID", "DOB", "Gender", "Mobile_No", "Course", "Photo Path", "Photo"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        student_tbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                student_tblMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(student_tbl);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(54, 145, 982, 172));

        jLabel1.setFont(new java.awt.Font("Serif", 1, 24)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/student page icon.png"))); // NOI18N
        jLabel1.setText("STUDENT INFO.");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(406, 6, -1, 81));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("USER-ID :");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(77, 104, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("COURSE :");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 360, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("EMAIL-ID :");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(129, 399, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("DOB :");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(163, 471, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("NAME :");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(151, 353, -1, -1));

        uid1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        getContentPane().add(uid1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 101, 218, -1));

        fetch1.setBackground(new java.awt.Color(0, 153, 255));
        fetch1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        fetch1.setText("FETCH");
        fetch1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        fetch1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        fetch1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fetch1ActionPerformed(evt);
            }
        });
        getContentPane().add(fetch1, new org.netbeans.lib.awtextra.AbsoluteConstraints(406, 101, -1, -1));

        back1.setBackground(new java.awt.Color(255, 153, 102));
        back1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        back1.setText("<- BACK");
        back1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        back1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        back1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                back1ActionPerformed(evt);
            }
        });
        getContentPane().add(back1, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 20, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("PHOTO PATH :");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 410, -1, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setText("PHOTO :");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 470, -1, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setText("GENDER :");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(136, 518, -1, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setText("MOBILE_NUMBER :");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(72, 573, -1, -1));

        path1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        getContentPane().add(path1, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 410, 218, 28));

        name1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        getContentPane().add(name1, new org.netbeans.lib.awtextra.AbsoluteConstraints(251, 349, 218, 28));

        mobile1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        getContentPane().add(mobile1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 569, 229, 28));

        email1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        getContentPane().add(email1, new org.netbeans.lib.awtextra.AbsoluteConstraints(251, 395, 218, 28));
        getContentPane().add(dob11, new org.netbeans.lib.awtextra.AbsoluteConstraints(251, 461, 218, 30));

        buttonGroup1.add(male1);
        male1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        male1.setText("MALE");
        getContentPane().add(male1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 520, 98, -1));

        buttonGroup1.add(female1);
        female1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        female1.setText("FEMALE");
        getContentPane().add(female1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 520, 98, -1));

        course1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        getContentPane().add(course1, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 360, 229, -1));
        getContentPane().add(photo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 470, 117, 126));

        clear1.setBackground(new java.awt.Color(255, 102, 0));
        clear1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        clear1.setText("CLEAR");
        clear1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        clear1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        clear1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clear1ActionPerformed(evt);
            }
        });
        getContentPane().add(clear1, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 520, 100, -1));

        close1.setBackground(new java.awt.Color(255, 0, 0));
        close1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        close1.setText("CLOSE");
        close1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        close1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        close1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                close1ActionPerformed(evt);
            }
        });
        getContentPane().add(close1, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 580, 101, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/background.jpg"))); // NOI18N
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1080, 710));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void fetch1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fetch1ActionPerformed
        DefaultTableModel model = (DefaultTableModel) student_tbl.getModel();
        String uid = uid1.getText();
        if (!uid.isEmpty()) {
            try (Connection conn = JDBC.con(); PreparedStatement pst = conn.prepareStatement("sp_sms_student_getbyid ?")) {
                pst.setString(1, uid);
                ResultSet rs = pst.executeQuery();
                model.setRowCount(0);
                SimpleDateFormat df = new SimpleDateFormat("yyyy:MM:dd");

                while (rs.next()) {
                    String user_ID = rs.getString("user_id");
                    String NAME = rs.getString("name");
                    String Email = rs.getString("email_id");

                    java.sql.Date dob1 = rs.getDate("dob");
                    String date = df.format(dob1);

                    String Gender = rs.getString("gender");
                    String Mobile = rs.getString("mobilr_no");
                    String cor = rs.getString("course");

                    String photopath = rs.getString("photo_path");
                    ImageIcon imageicon = null;
                    if (new File(photopath).exists()) {
                        Image img = new ImageIcon(photopath).getImage();
                        Image ScaledImage = img.getScaledInstance(100, 300, Image.SCALE_SMOOTH);
                        imageicon = new ImageIcon(ScaledImage);

                    }
                    model.addRow(new Object[]{user_ID, NAME, Email, date, Gender, Mobile, cor, photopath, imageicon});
                    course1.addItem(cor);
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, e);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Enter User-id");
        }
    }//GEN-LAST:event_fetch1ActionPerformed

    private void student_tblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_student_tblMouseClicked
        DefaultTableModel model = (DefaultTableModel) student_tbl.getModel();
        try {

            int row = 0;
            row = student_tbl.rowAtPoint(evt.getPoint());

            String USER_ID = student_tbl.getValueAt(row, 0).toString();
            String NAME = student_tbl.getValueAt(row, 1).toString();
            String EMAIL_ID = student_tbl.getValueAt(row, 2).toString();
            String dob1 = (String) student_tbl.getValueAt(row, 3);
            java.util.Date utildate = new SimpleDateFormat("yyyy:MM:dd").parse(dob1);
            String GENDER = student_tbl.getValueAt(row, 4).toString();
            String MOBILE = student_tbl.getValueAt(row, 5).toString();
            String COURSE = student_tbl.getValueAt(row, 6).toString();
            String PHOTO_PATH = student_tbl.getValueAt(row, 7).toString();

            uid1.setText(USER_ID);
            name1.setText(NAME);
            email1.setText(EMAIL_ID);
            dob11.setDate(utildate);

            if ("Male".equalsIgnoreCase(GENDER)) {
                male1.setSelected(true);
            } else if ("Female".equalsIgnoreCase(GENDER)) {
                female1.setSelected(true);
            }
            mobile1.setText(MOBILE);
            course1.setSelectedItem(COURSE);
            path1.setText(PHOTO_PATH);
            photo1.setIcon(new ImageIcon(new ImageIcon(PHOTO_PATH).getImage().getScaledInstance(photo1.getWidth(), photo1.getHeight(),
                    Image.SCALE_SMOOTH)));
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e);
        }
    }//GEN-LAST:event_student_tblMouseClicked

    private void back1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_back1ActionPerformed
        this.setVisible(false);
        new main_page().setVisible(true);
    }//GEN-LAST:event_back1ActionPerformed

    private void clear1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clear1ActionPerformed
        this.setVisible(false);
        new Student_page().setVisible(true);
    }//GEN-LAST:event_clear1ActionPerformed

    private void close1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_close1ActionPerformed
        this.setVisible(false);
            }//GEN-LAST:event_close1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Student_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Student_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Student_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Student_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Student_page().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back1;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton clear1;
    private javax.swing.JButton close1;
    private javax.swing.JComboBox<String> course1;
    private com.toedter.calendar.JDateChooser dob11;
    private javax.swing.JTextField email1;
    private javax.swing.JRadioButton female1;
    private javax.swing.JButton fetch1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton male1;
    private javax.swing.JTextField mobile1;
    private javax.swing.JTextField name1;
    private javax.swing.JTextField path1;
    private javax.swing.JLabel photo1;
    private javax.swing.JTable student_tbl;
    private javax.swing.JTextField uid1;
    // End of variables declaration//GEN-END:variables
}
